name: CI
env:
    SCREENER_API_KEY: ${{secrets.SCREENER_API_KEY}}
    SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
    SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version}}

            - name: install dependencies
              run: |
                  # cd jest-react-testing
                  npm ci
            - name: Build the app
              run: |
                  # cd jest-react-testing
                  npm run build
            - name: Start the app
              run: |
                  # cd jest-react-testing
                  # npm start &&
                  # npm wait-on --timeout 60000
